name: Flutter CI

on:
  create:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - run: echo $SIGNING_KEY | base64 -d > android/app/key.jks
        env:
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}    
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '1.26.0-17.8.pre'
          channel: 'beta'
      - run: flutter pub get
      - run: flutter build apk --target-platform android-arm --split-per-abi
        env:
          KEY_STORE_PASSWORD: ${{ secrets.KEY_STORE_PASSWORD }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          ALIAS: ${{ secrets.ALIAS }}
          KEY_PATH: key.jks
      - id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.ACTION_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
      - uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.ACTION_TOKEN }}
        with:
          releaseId: ${{ steps.create_release.outputs.id }}
          args: 'build/app/outputs/apk/release/app-armeabi-v7a-release.apk'
